# Generated by Django 4.1.7 on 2023-03-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_knives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=350),
        ),
    ]
