# Generated by Django 4.1.7 on 2023-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_knives', '0003_category_product_blade_length_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
