# Generated by Django 4.1.7 on 2023-03-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_knives', '0004_remove_category_description_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='blade_length',
        ),
    ]
